-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pytgrp3_progra
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pytgrp3_progra` ;

-- -----------------------------------------------------
-- Schema pytgrp3_progra
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pytgrp3_progra` DEFAULT CHARACTER SET utf8 ;
USE `pytgrp3_progra` ;


-- -----------------------------------------------------
-- Table `pytgrp3_progra`.`pytgrp5_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pytgrp3_progra`.`pytgrp5_person` (
  `person_id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(10) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `mail` VARCHAR(100) NULL,
  `active` TINYINT NULL DEFAULT 1,
  `write_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`person_id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;